// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itaechlpkrvaccxyeaud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0YWVjaGxwa3J2YWNjeHllYXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODE2NjksImV4cCI6MjA2MTE1NzY2OX0.ZUmObRVDx4jtbJiGeZj4e3JkK_rQpFfV2bSP0c-68_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);